<a href="https://colab.research.google.com/github/AlexeySergeychuk/SBER_DS/blob/main/DZ4%22Part_1_HW_Write_our_own_library_ipynb%22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Домашнее задание. Часть 1.

- напишем свою собственную библиотеку

Вего за эту часть ДЗ можно набрать максимум **11.5 баллов**. Разбиение баллов по каждой из задач представлено непосредственно перед текстом каждой задачи.

**Дедлайн - пятница, 11.12.2020 в 23:59.**

Дедлайн жесткий, сдача после дедлайна - 0 баллов за ДЗ.

Ссылка на ноутбук в колабе: https://colab.research.google.com/drive/1LgWtESFmiNW1WlVFCHKyNl_BxAWxoL3Z?usp=sharing

Допустим мы хотим написать фнкцию, которая складывает 2 числа и сохранить ее в отдельный .py файл. Пример:

In [ ]:
%%writefile lib.py
def summ(a1, b1):
    return a1+b1

Writing lib.py


In [ ]:
from lib import summ

In [ ]:
summ(2,6)

8

Попробуем запустить через "терминал"

In [ ]:
!python3 lib.py

Ничего не происходит. А теперь добавим `if __name__ == "__main__"` в наш код и пересохраним файл lib.py

In [ ]:
%%writefile lib.py
import sys

a1 = float( sys.argv[1] ) # Считываем аргументы прямо из терминала
b1 = float( sys.argv[2] ) # Считываем аргументы прямо из терминала

def summ(a1, b1):
    return a1+b1

if __name__ == "__main__":
    print(summ(a1, b1))


Writing lib.py


In [ ]:
!python3 lib.py 2 4

6.0


# **Задание 1**

Реализуйте следующие функции и сохраните их в библиотеку **my_math_lib.py** (пока без использования конструкции `if __name__ == "__main__"`)

**1 point** 
1. **def deg_to_rad()**. Напишите программу на Python для преобразования градусов в радианы.  *(Note: Радиан - это стандартная единица измерения угла, используемая во многих областях математики. Измерение угла в радианах численно равно длине соответствующей дуги единичного круга; один радиан чуть меньше 57,3 градуса)* **1 point**

**1 point** 
2. **def rad_to_def()**. Напишите программу Python для преобразования радианов в градусы.

**1.5 point** 
3. **def discriminant()**. Напишите программу на Python для вычисления значения дискриминанта (вспоминаем квадратные уравнения). Входные данные три числа: x, y, z (учтите что корни могут быть комлЕксными!)

**1.5 point** 
4. **def power_base_sum()**. Напишите программу на Python, чтобы вычислить сумму всех цифр основания в указанной степени.

Пример: power_base_sum(2, 100)

Выход: 115



**2 point** 
5. **def magic_square()**. Напишите программу на Python для вычисления [магического квадрата](https://ru.wikipedia.org/wiki/Магический_квадрат)

Note:

Магический, или волшебный квадрат — это квадратная таблица , заполненная числами таким образом, что сумма чисел в каждой строке, каждом столбце и на обеих диагоналях одинакова. Сумма чисел в каждой строке, столбце и на диагоналях, называется магической константой, M.

**1 point** 
6. **def mult_list()**. Напишите функцию Python для умножения всех чисел в массиве list(), (размер листа на входе произвольный)

**1 point** 
7. **def create_list()**. Напишите функцию Python для создания и вывода списка (при помощи print()), в котором значения представляют собой квадрат чисел от 1 до 30 (оба включительно).

In [ ]:

def deg_to_rad(grad):
  from math import pi
  x = (grad * pi)/ 180
  return x
deg_to_rad(47)

0.8203047484373349

In [ ]:
def rad_to_def(rad):
  from math import pi
  x = (rad * 180)/ pi
  return x
rad_to_def(3.2)

183.34649444186343

In [ ]:
def discriminant(a, b, c):
  d = b**2 - 4 * a * c
  return d
discriminant(1, -1, 2)


-7

In [ ]:
def power_base_sum(a, b):
  t = sum([int(i) for i in str(a ** b)])
  return t
power_base_sum(2, 100)

115

In [43]:
def magic_square(n):
  import numpy
  first = (n-1)/2
  mat = numpy.zeros([n,n])
  for i in range(n):
      mat[i][i] = first
      for j in range(n):
          if j < first:
              if i + j + 1 < n:
                  mat[i][i + j + 1] = j
              else:
                  mat[i][i + j + 1 - n] = j
          else:
              if j != first:
                  if j + i < n:
                      mat[i][i+j] = j
                  else:
                      mat[i][i+j-n] = j
              else:
                  pass

  mat1=numpy.zeros([n,n])
  for i in range(n):
      for j in range(n):
          mat1[i][j]=mat[i][j]*n+mat[i][n-1-j]+1
  return mat1
magic_square(5)

array([[15.,  4.,  7., 16., 23.],
       [24., 12.,  1.,  8., 20.],
       [17., 21., 13.,  5.,  9.],
       [ 6., 18., 25., 14.,  2.],
       [ 3., 10., 19., 22., 11.]])

In [ ]:
def mult_list(somelist):
  x = 1
  for i in somelist:
    x *= i
  return x
mult_list([1,2,3])


6

In [ ]:
def create_list():
  x = [i ** 2 for i in range(1, 31)]
  print(x)
create_list()

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576, 625, 676, 729, 784, 841, 900]


In [44]:
%%writefile my_math_lib.py

def deg_to_rad(grad):
  from math import pi
  x = (grad * pi)/ 180
  return x

def rad_to_def(rad):
  from math import pi
  x = (rad * 180)/ pi
  return x

def discriminant(a, b, c):
  d = b**2 - 4 * a * c
  return d

def power_base_sum(a, b):
  t = sum([int(i) for i in str(a ** b)])
  return t

def magic_square(n):
  import numpy
  first = (n-1)/2
  mat = numpy.zeros([n,n])
  for i in range(n):
      mat[i][i] = first
      for j in range(n):
          if j < first:
              if i + j + 1 < n:
                  mat[i][i + j + 1] = j
              else:
                  mat[i][i + j + 1 - n] = j
          else:
              if j != first:
                  if j + i < n:
                      mat[i][i+j] = j
                  else:
                      mat[i][i+j-n] = j
              else:
                  pass

  mat1=numpy.zeros([n,n])
  for i in range(n):
      for j in range(n):
          mat1[i][j]=mat[i][j]*n+mat[i][n-1-j]+1
  return mat1

def mult_list(somelist):
  x = 1
  for i in somelist:
    x *= i
  return x

def create_list():
  x = [i ** 2 for i in range(1, 31)]
  print(x)




Overwriting my_math_lib.py


# **Задание 2**
Импортируйте все методы из модуля my_math_lib.

 **0.25 point** 
 - при помощи функции **def discriminant()** посчитайте дискриминант следующего уравнения: 
 $x^{2}+3 x+4=0$

**0.25 point** 
 - постройте магический квадрат размера 5х5

In [49]:
from my_math_lib import *
discriminant(1, 3, 4)

-7

In [50]:
 magic_square(6)

array([[21. ,  5. , 10. , 20. , 25. , 33.5],
       [35. , 19. ,  2. ,  7. , 21.5, 30. ],
       [28. , 32. , 16. ,  3.5, 12. , 23. ],
       [20. , 25. , 33.5, 21. ,  5. , 10. ],
       [ 7. , 21.5, 30. , 35. , 19. ,  2. ],
       [ 3.5, 12. , 23. , 28. , 32. , 16. ]])

In [51]:
 magic_square(5)

array([[15.,  4.,  7., 16., 23.],
       [24., 12.,  1.,  8., 20.],
       [17., 21., 13.,  5.,  9.],
       [ 6., 18., 25., 14.,  2.],
       [ 3., 10., 19., 22., 11.]])

# **Задание 3**

**2 point**
* Добавьте в вашу библиотеку конструкцию `if __name__ == "__main__"`, которая должна принимать одну из вышеперечисленных функций. 
* Важно! аргументы, подаваемые в функцию, должны подаваться напряму через терминал (как в примере)! Используйте для этого библиотеку `sys`

In [54]:
%%writefile my_math_lib.py
import sys

def deg_to_rad(grad):
  from math import pi
  x = (grad * pi)/ 180
  return x

def rad_to_def(rad):
  from math import pi
  x = (rad * 180)/ pi
  return x

def discriminant(a, b, c):
  d = b**2 - 4 * a * c
  return d

def power_base_sum(a, b):
  t = sum([int(i) for i in str(a ** b)])
  return t

def magic_square(n):
  import numpy
  first = (n-1)/2
  mat = numpy.zeros([n,n])
  for i in range(n):
      mat[i][i] = first
      for j in range(n):
          if j < first:
              if i + j + 1 < n:
                  mat[i][i + j + 1] = j
              else:
                  mat[i][i + j + 1 - n] = j
          else:
              if j != first:
                  if j + i < n:
                      mat[i][i+j] = j
                  else:
                      mat[i][i+j-n] = j
              else:
                  pass

  mat1=numpy.zeros([n,n])
  for i in range(n):
      for j in range(n):
          mat1[i][j]=mat[i][j]*n+mat[i][n-1-j]+1
  return mat1

def mult_list(somelist):
  x = 1
  for i in somelist:
    x *= i
  return x

def create_list():
  x = [i ** 2 for i in range(1, 31)]
  print(x)

n = int(sys.argv[1])

if __name__ == "__main__":
    print(magic_square(n))

Overwriting my_math_lib.py


In [55]:
# Пример вызова функции - Вы можете вызвать любую другую
!python3 my_math_lib.py 5 # Например если в __main__ вы указали def discriminant()

[[15.  4.  7. 16. 23.]
 [24. 12.  1.  8. 20.]
 [17. 21. 13.  5.  9.]
 [ 6. 18. 25. 14.  2.]
 [ 3. 10. 19. 22. 11.]]
